CONF=$(dirname "${BASH_SOURCE[0]}")
source $CONF/testbed.sh


#ROS
ROS_MASTER=$LOCALHOST
ROS_MASTER_NICE="-10"
ROS_MASTER_CPUS="0"
ROS_MASTER_URI="http://$LOCALHOST:11311"
ROS_IP_MASTER=$LOCALHOST

ROS_PING=$LOCALHOST
ROS_PING_NICE="-10"
ROS_PING_CPUS="1"
ROS_IP_PING=$LOCALHOST

ROS_PONG=$LOCALHOST
ROS_PONG_NICE="-10"
ROS_PONG_CPUS="2"
ROS_IP_PONG=$LOCALHOST

#ROS2

ROS2_PING=$LOCALHOST
ROS2_PING_NICE="-10"
ROS2_PING_CPUS="0"
ROS2_PING_CYCLONEDDS_URI=$LOCALHOST_CYCLONEDDS_URI

ROS2_PONG=$LOCALHOST
ROS2_PONG_NICE="-10"
ROS2_PONG_CPUS="1"
ROS2_PONG_CYCLONEDDS_URI=$LOCALHOST_CYCLONEDDS_URI

# Zenoh
Z_PING=$LOCALHOST
Z_PING_NICE="-10"
Z_PING_CPUS="0"

Z_PONG=$LOCALHOST
Z_PONG_NICE="-10"
Z_PONG_CPUS="1"

Z_ROUTER=$LOCALHOST


LOCATOR_PING="udp/127.0.0.1:7007"
LOCATOR_PONG="udp/127.0.0.1:7447"


# Kafka

K_PING=$LOCALHOST
K_PING_NICE="-10"
K_PING_CPUS="0"

K_PONG=$LOCALHOST
K_PONG_NICE="-10"
K_PONG_CPUS="1"

K_BROKER=$LOCALHOST
K_BROKER_IP=$LOCALHOST

# MQTT

M_PING=$LOCALHOST
M_PING_NICE="-10"
M_PING_CPUS="0"

M_PONG=$LOCALHOST
M_PONG_NICE="-10"
M_PONG_CPUS="1"

M_BROKER=$LOCALHOST
M_BROKER_IP=$LOCALHOST
