CONF=$(dirname "${BASH_SOURCE[0]}")
source $CONF/testbed.sh


#ROS
ROS_MASTER=$MINIPC
ROS_MASTER_NICE="-10"
ROS_MASTER_CPUS="0"
ROS_MASTER_URI="http://$MINIPC_MMWAVE:11311"
ROS_IP_MASTER=$MINIPC_MMWAVE

ROS_PING=$UNIPI4
ROS_PING_NICE="-10"
ROS_PING_CPUS="1"
ROS_IP_PING=$UNIPI4_MMWAVE

ROS_PONG=$MINIPC
ROS_PONG_NICE="-10"
ROS_PONG_CPUS="1"
ROS_IP_PONG=$MINIPC_MMWAVE

#ROS2

ROS2_PING=$UNIPI4
ROS2_PING_NICE="-10"
ROS2_PING_CPUS="0"
ROS2_PING_CYCLONEDDS_URI=$LOCALHOST_CYCLONEDDS_URI

ROS2_PONG=$MINIPC
ROS2_PONG_NICE="-10"
ROS2_PONG_CPUS="1"
ROS2_PONG_CYCLONEDDS_URI=$LOCALHOST_CYCLONEDDS_URI

# Zenoh
Z_PING=$UNIPI4
Z_PING_NICE="-10"
Z_PING_CPUS="0"

Z_PONG=$MINIPC
Z_PONG_NICE="-10"
Z_PONG_CPUS="1"

Z_ROUTER=$MINIPC


LOCATOR_PING="udp/$UNIPI4_MMWAVE:7007"
LOCATOR_PONG="udp/$MINIPC_MMWAVE:7447"


# Kafka

K_PING=$UNIPI4
K_PING_NICE="-10"
K_PING_CPUS="0"

K_PONG=$MINIPC
K_PONG_NICE="-10"
K_PONG_CPUS="1"

K_BROKER=$MINIPC
K_BROKER_IP=$MINIPC_MMWAVE


# MQTT

M_PING=$UNIPI4
M_PING_NICE="-10"
M_PING_CPUS="0"

M_PONG=$MINIPC
M_PONG_NICE="-10"
M_PONG_CPUS="1"

M_BROKER=$MINIPC
M_BROKER_IP=$MINIPC_MMWAVE
