CONF=$(dirname "${BASH_SOURCE[0]}")
source $CONF/testbed.sh


#ROS
ROS_MASTER=$MINIPC
ROS_MASTER_NICE="-10"
ROS_MASTER_CPUS="0"
ROS_MASTER_URI="http://$MINIPC_WIFI6:11311"
ROS_IP_MASTER=$MINIPC_WIFI6

ROS_PING=$UNIPI422
ROS_PING_NICE="-10"
ROS_PING_CPUS="1"
ROS_IP_PING=$UNIPI42_MMWAVE

ROS_PONG=$MINIPC
ROS_PONG_NICE="-10"
ROS_PONG_CPUS="1"
ROS_IP_PONG=$MINIPC_MMWAVE

#ROS2

ROS2_PING=$UNIPI42
ROS2_PING_NICE="-10"
ROS2_PING_CPUS="0"
ROS2_PING_CYCLONEDDS_URI=$PI_WIFI6_CYCLONEDDS_URI

ROS2_PONG=$MINIPC
ROS2_PONG_NICE="-10"
ROS2_PONG_CPUS="1"
ROS2_PONG_CYCLONEDDS_URI=$MINIPC_WIFI6_CYCLONEDDS_URI

# Zenoh
Z_PING=$UNIPI42
Z_PING_NICE="-10"
Z_PING_CPUS="0"

Z_PONG=$MINIPC
Z_PONG_NICE="-10"
Z_PONG_CPUS="1"

Z_ROUTER=$MINIPC


LOCATOR_PING="udp/$PI_WIFI6:7007"
LOCATOR_PONG="udp/$MINIPC_WIFI6:7447"


# Kafka

K_PING=$UNIPI42
K_PING_NICE="-10"
K_PING_CPUS="0"

K_PONG=$MINIPC
K_PONG_NICE="-10"
K_PONG_CPUS="1"

K_BROKER=$MINIPC
K_BROKER_IP=$MINIPC_WIFI6


# MQTT

M_PING=$UNIPI42
M_PING_NICE="-10"
M_PING_CPUS="0"

M_PONG=$MINIPC
M_PONG_NICE="-10"
M_PONG_CPUS="1"

M_BROKER=$MINIPC
M_BROKER_IP=$MINIPC_WIFI6
