CONF=$(dirname "${BASH_SOURCE[0]}")
source $CONF/testbed.sh


#ROS
ROS_MASTER=$JETSON
ROS_MASTER_NICE="-10"
ROS_MASTER_CPUS="0"
ROS_MASTER_URI="http://$JETSON_WIFI:11311"
ROS_IP_MASTER=$JETSON_WIFI

ROS_PING=$PI4
ROS_PING_NICE="-10"
ROS_PING_CPUS="1"
ROS_IP_PING=$PI4_WIFI

ROS_PONG=$JETSON
ROS_PONG_NICE="-10"
ROS_PONG_CPUS="1"
ROS_IP_PONG=$JETSON_WIFI

#ROS2

ROS2_PING=$PI4
ROS2_PING_NICE="-10"
ROS2_PING_CPUS="0"
ROS2_PING_CYCLONEDDS_URI=$PI_WIFI_CYCLONEDDS_URI

ROS2_PONG=$JETSON
ROS2_PONG_NICE="-10"
ROS2_PONG_CPUS="1"
ROS2_PONG_CYCLONEDDS_URI=$JETSON_WIFI_CYCLONEDDS_URI

# Zenoh
Z_PING=$PI4
Z_PING_NICE="-10"
Z_PING_CPUS="0"

Z_PONG=$JETSON
Z_PONG_NICE="-10"
Z_PONG_CPUS="1"

Z_ROUTER=$JETSON


LOCATOR_PING="udp/$PI4_WIFI:7007"
LOCATOR_PONG="udp/$JETSON_WIFI:7447"


# Kafka

K_PING=$PI4
K_PING_NICE="-10"
K_PING_CPUS="0"

K_PONG=$JETSON
K_PONG_NICE="-10"
K_PONG_CPUS="1"

K_BROKER=$JETSON
K_BROKER_IP=$JETSON_WIFI

# MQTT

M_PING=$PI4
M_PING_NICE="-10"
M_PING_CPUS="0"

M_PONG=$JETSON
M_PONG_NICE="-10"
M_PONG_CPUS="1"

M_BROKER=$JETSON
M_BROKER_IP=$LAPTOJETSON_WIFI_WIFI
